# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestP1():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_p1(self):
    # Test name: P1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1440x804 | 
    self.driver.set_window_size(1440, 804)
    # 3 | click | id=APjFqb | 
    self.driver.find_element(By.ID, "APjFqb").click()
    # 4 | click | css=#jZ2SBf > .wM6W7d > span | 
    self.driver.find_element(By.CSS_SELECTOR, "#jZ2SBf > .wM6W7d > span").click()
    # 5 | runScript | window.scrollTo(0,68) | 
    self.driver.execute_script("window.scrollTo(0,68)")
    # 6 | runScript | window.scrollTo(0,309) | 
    self.driver.execute_script("window.scrollTo(0,309)")
    # 7 | click | css=.MjjYud:nth-child(5) .LC20lb | 
    self.driver.find_element(By.CSS_SELECTOR, ".MjjYud:nth-child(5) .LC20lb").click()
    # 8 | click | css=.pageWrapper_ca2kA | 
    self.driver.find_element(By.CSS_SELECTOR, ".pageWrapper_ca2kA").click()
  
