# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
options = Options()

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)


class TestTrytesting():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

    # self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_trytesting(self):
    # Test name: try_testing
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://qbrow.rasree.com/")
    # 2 | setWindowSize | 1440x804 | 
    self.driver.set_window_size(1440, 804)
    # 3 | click | css=.kjsDg > .bWxOKe | 
    self.driver.find_element(By.CSS_SELECTOR, ".kjsDg > .bWxOKe").click()
    # 4 | type | id=username | Priya3457
    self.driver.find_element(By.ID, "username").send_keys("Priya3457")
    # 5 | type | id=password | Priya
    self.driver.find_element(By.ID, "password").send_keys("Priya")
    # 6 | click | id=kc-form-wrapper | 
    self.driver.find_element(By.ID, "kc-form-wrapper").click()
    # 7 | type | id=username | admin_a
    self.driver.find_element(By.ID, "username").send_keys("admin_a")
    # 8 | click | id=kc-form-wrapper | 
    self.driver.find_element(By.ID, "kc-form-wrapper").click()
    # 9 | type | id=password | password
    self.driver.find_element(By.ID, "password").send_keys("password")
    # 10 | click | id=kc-login | 
    self.driver.find_element(By.ID, "kc-login").click()
    # 11 | runScript | window.scrollTo(0,245) | 
    self.driver.execute_script("window.scrollTo(0,245)")
    # 12 | runScript | window.scrollTo(0,663) | 
    self.driver.execute_script("window.scrollTo(0,663)")
    # 13 | runScript | window.scrollTo(0,733) | 
    self.driver.execute_script("window.scrollTo(0,733)")
    # 14 | runScript | window.scrollTo(0,343) | 
    self.driver.execute_script("window.scrollTo(0,343)")
    # 15 | click | css=.gEAsKT > .bWxOKe | 
    self.driver.find_element(By.CSS_SELECTOR, ".gEAsKT > .bWxOKe").click()
    # 16 | click | css=.dTuERj:nth-child(1) .bWxOKe | 
    self.driver.find_element(By.CSS_SELECTOR, ".dTuERj:nth-child(1) .bWxOKe").click()
    # 17 | click | css=#profileBtn > .iZqLUj | 
    self.driver.find_element(By.CSS_SELECTOR, "#profileBtn > .iZqLUj").click()
    # 18 | click | css=.Ovxqx:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".Ovxqx:nth-child(5)").click()
  
