# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select

class TestCreateCourseTest():
  '''
  - This is automation testing of create course page.
  - There are 3 methods which is executed in class TestCreateCourseTest, \
  which are setup_method, teardown_method and test_create_course.
  '''

  def setup_method(self, method):
    '''Set up the test environment before each test method runs
    - webdriver.Chrome class is used to create an instance of the Chrome browser driver.
    '''
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    '''
    - Clean up after each test method finishes.
    - self.driver.quit() is called.
    - This command tells Selenium to close and quit the web browser and release any associated resources.
    '''
    self.driver.quit()
  
  def test_create_course(self):
    '''
    - Test name: TestCreateCourseTest
    Step # | name | target | value
    - Each step is very well describe by dividing into small steps
     and  applying comments on each steps. 
     - Assert statements are been added to ensure each step is executed as expected.
    '''
    
    # Creating instance of WebDriverWait class.
    wait = WebDriverWait(self.driver, 60)

    # 1 | open | / | Go to URL https://qbrow.rasree.com/
    self.driver.get("https://qbrow.rasree.com/")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1440, 804)

    expected_title = "Home | Rasree"
    assert expected_title in self.driver.title, f"Page title '{self.driver.title}'\
          does not match expected title '{expected_title}'"

    # 3 | click | id=inputSignInButton | 
    # Click on sign-in button
    self.driver.find_element(By.ID, "inputSignInButton").click()

    expected_title = "Rasree Login Page"
    assert expected_title in self.driver.title, f"Page title '{self.driver.title}'\
          does not match expected title '{expected_title}'"

    # 4 | type | id=username | admin_a
    # Enter username admin_a
    self.driver.find_element(By.ID, "username").send_keys("admin_a")

    username_text = self.driver.find_element(By.ID, "username").get_attribute("value")
    assert username_text == "admin_a", f"username text is '{username_text}', expected 'admin_a'"

    # 5 | click | id=password | 
    # click on input box of password
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | password
    # Type password
    self.driver.find_element(By.ID, "password").send_keys("password")

    password_text = self.driver.find_element(By.ID, "password").get_attribute("value")
    assert password_text == "password", f"password text is '{password_text}', expected 'password'"

    # 7 | click | id=kc-login | 
    # click on login button
    self.driver.find_element(By.ID, "kc-login").click()

    expected_login_page_url = "https://qbrow.rasree.com/"
    assert expected_login_page_url == self.driver.current_url, f"URL '{self.driver.current_url}'\
          does not match expected URL '{expected_login_page_url}'"
        
    # 8 | click | id=inputmenumodalbtn | 
    # click on menu modal
    wait.until(EC.element_to_be_clickable((By.ID,"inputmenumodalbtn"))).click()

    # 9 | click | id=inputCreateCourseButton | 
    # click on create button

    self.driver.find_element(By.ID, "inputCreateCourseButton").click()

    expected_login_page_url = "https://qbrow.rasree.com/course-create"
    assert expected_login_page_url == self.driver.current_url, f"URL '{self.driver.current_url}'\
          does not match expected URL '{expected_login_page_url}'"
        
    # 10 | click | id=inputBasicInfoCourseTitle | 
    # click on basic info button.
    wait.until(EC.element_to_be_clickable((By.ID,"inputBasicInfoCourseTitle"))).click()
 
    # 12 | type | id=inputBasicInfoCourseTitle | Org_Public_1_Maths_CBSE_10th
    # send keys to  course title
    self.driver.find_element(By.ID, "inputBasicInfoCourseTitle").send_keys("Org_Public_1_Maths_CBSE_10th")

    course_title_text = self.driver.find_element(By.ID, "inputBasicInfoCourseTitle").get_attribute("value")
    assert course_title_text == "Org_Public_1_Maths_CBSE_10th", f"Search bar text is '{course_title_text}', expected 'Org_Public_1_Maths_CBSE_10th'"


    # 13 | click | id=inputBasicInfoCourseDescription | 
    # click on  course description
    self.driver.find_element(By.ID, "inputBasicInfoCourseDescription").click()

    # 14 | type | id=inputBasicInfoCourseDescription | Basics of Algerbra
    # enter course description
    self.driver.find_element(By.ID, "inputBasicInfoCourseDescription").send_keys("Basics of Algerbra")

    course_desc_text = self.driver.find_element(By.ID, "inputBasicInfoCourseDescription").get_attribute("value")
    assert course_desc_text == "Basics of Algerbra", f"Search bar text is '{course_desc_text}', expected 'Basics of Algerbra'"


    # 15 | click | id=inputBasicInfoCourseSubject | 
    # click on subject : Maths
    time.sleep(5)
    # wait.until(EC.element_to_be_clickable((By.ID,"inputBasicInfoCourseSubject")))

    subject_dropdown =   self.driver.find_element(By.ID, "inputBasicInfoCourseSubject")
    select_subject_from_drop_down = Select(subject_dropdown)
    select_subject_from_drop_down.select_by_value("Math")

    selected_subject_option = select_subject_from_drop_down.first_selected_option
    assert selected_subject_option.text == "Math", f"Expected 'Math' to be selected, but actual selection is '{selected_subject_option.text}'"


    # 16 | click | id=inputBasicInfoCourseCurriculum | 
    # click on curriculum

    curriculum_dropdown= wait.until(EC.element_to_be_clickable((By.ID,"inputBasicInfoCourseCurriculum")))

    # curriculum_dropdown = self.driver.find_element(By.ID, "inputBasicInfoCourseCurriculum")
  
    select_curriculum_from_drop_down = Select(curriculum_dropdown)
    select_curriculum_from_drop_down.select_by_value("CBSE")

    selected_curriculum_option = select_curriculum_from_drop_down.first_selected_option
    assert selected_curriculum_option.text == "CBSE", f"Expected 'CBSE' to be selected, but actual selection is '{selected_curriculum_option.text}'"

    # 17 | click | id=inputBasicInfoCourseGrade | 
    # click on grade

    grade_dropdown = self.driver.find_element(By.ID, "inputBasicInfoCourseGrade")
    select_grade_from_drop_down = Select(grade_dropdown)
    select_grade_from_drop_down.select_by_value("10th")

    selected_grade_option = select_grade_from_drop_down.first_selected_option
    assert selected_grade_option.text == "10th", f"Expected '10th' to be selected, but actual selection is '{selected_grade_option.text}'"


    # 18 | select | id=inputBasicInfoCourseTutor | label=tutor_math_a
    # select tutor_math_a

    tutor_dropdown = self.driver.find_element(By.ID, "inputBasicInfoCourseTutor")
    select_tutor_from_drop_down = Select(tutor_dropdown)
    select_tutor_from_drop_down.select_by_value("ff72fa64-e379-4762-97f3-9cc6ce29b853")

    selected_tutor_option = select_tutor_from_drop_down.first_selected_option
    assert selected_tutor_option.text == "tutor_math_a", f"Expected tutor math_a to be selected, but actual selection is '{selected_tutor_option.text}'"


    # 27 | click | id=inputSaveBasicInfo | 
    # click on save basic info
    self.driver.find_element(By.ID, "inputSaveBasicInfo").click()

    # 29 | type | id=inputScheduleInfoStartDate | 2023-08-04
    # # click on start date
    # time.sleep(6)
    # start_date_input = self.driver.find_element(By.ID, "inputScheduleInfoStartDate").click()
    # time.sleep(6)
    # start_date_input.send_keys("04/08/2022")
    # print("****",start_date_input)
    # expected_start_date = "2023-08-04"
    # assert start_date_input.get_attribute("value") == expected_start_date, f"Entered start date '{start_date_input.get_attribute('value')}' does not match expected start date '{expected_start_date}'"



    # # 30 | click | id=inputScheduleInfoStartDate | 
    # # click on start date
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").click()

    # # 31 | click | id=inputScheduleInfoStartDate | 
    # # click on start date
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").click()

    # # 32 | click | id=inputScheduleInfoStartDate | 
    # # click on start date
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").click()

    # # 33 | click | id=inputScheduleInfoStartDate | 
    # # click on start date
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").click()

    # # 34 | doubleClick | id=inputScheduleInfoStartDate | 
    # # double click on start date
    # time.sleep(5)
    # element = self.driver.find_element(By.ID, "inputScheduleInfoStartDate")
    # actions = ActionChains(self.driver)
    # actions.double_click(element).perform()
    # # 35 | type | id=inputScheduleInfoStartDate | 0002-08-04
    # # select date from calendar 
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").send_keys("0002-08-04")
    # # 36 | type | id=inputScheduleInfoStartDate | 0020-08-04
    # # type start date 0020-08-04
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").send_keys("0020-08-04")
    # # 37 | type | id=inputScheduleInfoStartDate | 0202-08-0
    # # click on start date 0202-08-2
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").send_keys("0202-08-0")
    # # 38 | type | id=inputScheduleInfoStartDate | 2024-08-04
    # # type start date 2024-08-04
    # self.driver.find_element(By.ID, "inputScheduleInfoStartDate").send_keys("2024-08-04")
    # # 39 | click | id=inputScheduleInfoEndDate | 
    # # click on end date
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").click()
    # # 40 | click | id=inputScheduleInfoEndDate | 
    # # click on end date
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").click()
    # # 41 | type | id=inputScheduleInfoEndDate | 2023-08-06
    # # type end date 2023-08-06
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").send_keys("2023-08-06")
    # # 42 | click | id=inputScheduleInfoEndDate | 
    # # click on end date
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").click()
    # # 43 | click | id=inputScheduleInfoEndDate | 
    # # click on end date
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").click()
    # # 44 | click | id=inputScheduleInfoEndDate | 
    # # click on end date
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").click()
    # # 45 | type | id=inputScheduleInfoEndDate | 0002-08-06
    # # type end date 0020-08-06
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").send_keys("0002-08-06")
    # # 46 | type | id=inputScheduleInfoEndDate | 0020-08-06
    # # type end date 0020-08-06
    # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").send_keys("0020-08-06")
    # # 47 | type | id=inputScheduleInfoEndDate | 0202-08-06
    # # type end date 0202-08-06
    # # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").send_keys("0202-08-06")
    # # 48 | type | id=inputScheduleInfoEndDate | 2024-08-06
    # # enter end date 2024-08-04
    # # self.driver.find_element(By.ID, "inputScheduleInfoEndDate").send_keys("2024-08-06")
    # # 49 | click | id=spanDiv | 
    # # click on check box of monday
    # self.driver.find_element(By.ID, "spanDiv").click()
    # # 50 | click | css=#inputWeekname_Wednesday > #spanDiv | 
    # # click on check box of  wednesday
    # self.driver.find_element(By.CSS_SELECTOR, "#inputWeekname_Wednesday > #spanDiv").click()
    # # 51 | click | css=#inputWeekname_Friday > #spanDiv | 
    # # click on checkbox of friday
    # self.driver.find_element(By.CSS_SELECTOR, "#inputWeekname_Friday > #spanDiv").click()
    # # 52 | click | id=inputDefaultStartTime | 
    # # click on default start time
    # self.driver.find_element(By.ID, "inputDefaultStartTime").click()
    # # 53 | click | id=inputDefaultStartTime | 
    # # click on default start timer
    # self.driver.find_element(By.ID, "inputDefaultStartTime").click()
    # # 54 | type | id=inputDefaultStartTime | 12:00
    # # type 12:00
    # self.driver.find_element(By.ID, "inputDefaultStartTime").send_keys("12:00")
    # # 55 | click | id=inputDefaultSessionDuration | 
    # # click on session duration
    # self.driver.find_element(By.ID, "inputDefaultSessionDuration").click()
    # # 56 | mouseDownAt | id=inputDefaultSessionDuration | 44.90625,20.03125
    # element = self.driver.find_element(By.ID, "inputDefaultSessionDuration")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).click_and_hold().perform()
    # # 57 | mouseMoveAt | id=inputDefaultSessionDuration | 44.90625,20.03125
    # element = self.driver.find_element(By.ID, "inputDefaultSessionDuration")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # # 58 | mouseUpAt | id=inputDefaultSessionDuration | 44.90625,20.03125
    # element = self.driver.find_element(By.ID, "inputDefaultSessionDuration")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).release().perform()
    # # 59 | click | id=inputDefaultSessionDuration | 
    # # click on input box of session duration
    # self.driver.find_element(By.ID, "inputDefaultSessionDuration").click()
    # # 60 | click | id=inputDefaultSessionDuration | 
    # # click on default session duration
    # self.driver.find_element(By.ID, "inputDefaultSessionDuration").click()
    # # 61 | type | id=inputDefaultSessionDuration | 01:00
    # # enter 01:00
    # self.driver.find_element(By.ID, "inputDefaultSessionDuration").send_keys("01:00")
    # # 62 | click | id=inputSaveScheduleInfo | 
    # # click on continue button
    self.driver.find_element(By.ID, "inputSaveScheduleInfo").click()
    # # 63 | click | id=inputMinimumStudent | 
    # # click on minimum student
    self.driver.find_element(By.ID, "inputMinimumStudent").click()
    # # 64 | type | id=inputMinimumStudent | 2
    # # enter minimum student 2
    self.driver.find_element(By.ID, "inputMinimumStudent").send_keys("2")
    # # 65 | click | id=inputMaximumStudent | 
    # # click on maximum student
    self.driver.find_element(By.ID, "inputMaximumStudent").click()
    # # 66 | type | id=inputMaximumStudent | 10
    # # enter maximum student 210
    self.driver.find_element(By.ID, "inputMaximumStudent").send_keys("10")
    # # 67 | click | id=inputCoursePayment_1 | 
    # # click on course payment
    self.driver.find_element(By.ID, "inputCoursePayment_1").click()
    # # 68 | click | id=inputCurrency | 
    # # click on input currency
    self.driver.find_element(By.ID, "inputCurrency").click()
    # # 69 | select | id=inputCurrency | label=United States Dollar (USD)
    # select input currency USD
    dropdown = self.driver.find_element(By.ID, "inputCurrency")
    dropdown.find_element(By.XPATH, "//option[. = 'United States Dollar (USD)']").click()
    # # 70 | click | id=inputCourseFees | 
    # # click on course fee
    # self.driver.find_element(By.ID, "inputCourseFees").click()
    # # 71 | click | id=inputCurrency | 
    # # click on input currency 
    # self.driver.find_element(By.ID, "inputCurrency").click()
    # # 72 | select | id=inputCurrency | label=Indian Rupee (INR)
    # # enter Indian Rupee
    # dropdown = self.driver.find_element(By.ID, "inputCurrency")
    # dropdown.find_element(By.XPATH, "//option[. = 'Indian Rupee (INR)']").click()
    # # 73 | click | id=inputCourseFees | 
    # # click on course fee
    # self.driver.find_element(By.ID, "inputCourseFees").click()
    # # 74 | type | id=inputCourseFees | 2000
    # # type course fee 2000
    # self.driver.find_element(By.ID, "inputCourseFees").send_keys("2000")
    # # 75 | click | id=inputSavePriceEnrollInfo | 
    # # click on continue button
    # self.driver.find_element(By.ID, "inputSavePriceEnrollInfo").click()
    # # # 76 | click | id=inputSaveCourseAsReadyForApproval | 
    # # # Click on  save and  submit for approval.
    # # self.driver.find_element(By.ID, "inputSaveCourseAsReadyForApproval").click()
  
