# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)


class TestPage2Loginpage():
    ''' 
  DESCRIPTION: This test trys to login with an unregistered and registered UID & PWD
  PROCEDURE: 
  1. go to browser app
  2. click on sign in
  3. provide correct UI & PWD on login screen
  4. check if the login passed after the roundtrip to server
  5. redirect to user dashboard for registered
  EXPECTED OUTCOME: The login should pass for an registered user.
  '''
    def setup_method(self, method):
      self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
      self.vars = {}
    
    def teardown_method(self, method):
       self.driver.quit()
       
    def test_page2Loginpage(self):
      # Test name: Page_2_Login_page
      # Step # | name | target | value
      # 1 | open | / | 
      # go to url - https://qbrow.rasree.com
      self.driver.get("https://qbrow.rasree.com/")
      # 2 | setWindowSize | 1440x804 | 
      self.driver.set_window_size(1440, 804)

      # 3 | click | css=.bWxOKe:nth-child(1) | 
      # click on sign in button
      self.driver.find_element(By.CSS_SELECTOR, ".bWxOKe:nth-child(1)").click()

      # 4 | click | id=username | 
      self.driver.find_element(By.ID, "username").click()

      # enter correct User ID
      self.driver.find_element(By.ID, "username").send_keys("admin_a")
      # 5 | click | id=password | 
      self.driver.find_element(By.ID, "password").click()
      # 6 | type | id=password | password
      # enter correct password
      self.driver.find_element(By.ID, "password").send_keys("password")
      # 7 | click | id=kc-login | 
      self.driver.find_element(By.ID, "kc-login").click()
      # 8 | click | css=.iZqLUj | 
      # click on user profile option

      wait = WebDriverWait(self.driver, 60)
    
      profile_btn = wait.until(EC.presence_of_element_located((By.ID, "profileBtn")))
      profile_btn.click()

      # 9 | click | css=.Ovxqx:nth-child(5) | 
      # click on logout option
      wait1 = WebDriverWait(self.driver, 60)
      log_off_btn = wait1.until(EC.presence_of_element_located((By.XPATH,'//*[@id="inputProfileModal"]/div/button[4]')))
      log_off_btn.click()


      