# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)


class TestPage3browseSearchpagewithoutlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_page3browseSearchpagewithoutlogin(self):
    # Test name: page_3_browseSearch_page_without login
    # Step # | name | target | value
    # 1 | open | / | 
    # go to URL: qbrow rasree.com

    wait = WebDriverWait(self.driver, 60)
    

    self.driver.get("https://qbrow.rasree.com/")
    # 2 | setWindowSize | 1440x804 | 
    self.driver.set_window_size(1440, 804)
    # 3 | click | id=inputExploreBtn | 
    # click on explore oprion and it will redirect to browsesearch page
    self.driver.find_element(By.ID, "inputExploreBtn").click()
    # 4 | click | id=spanDiv | 
    # click on Math check box
    self.driver.find_element(By.ID, "spanDiv").click()
    # 5 | click | css=#filter_subject_2 > #spanDiv | 
    # click on science check box

    profile_btn = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#filter_subject_2 > #spanDiv")))
    profile_btn.click()


    # self.driver.find_element(By.CSS_SELECTOR, "#filter_subject_2 > #spanDiv").click()
    # # 6 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 7 | click | css=#filter_curriculum_5 > #spanDiv | 
    # # click on CBSE option
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_curriculum_5 > #spanDiv").click()
    # # 8 | click | css=#filter_curriculum_6 > #spanDiv | 
    # # click on ICSE option
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_curriculum_6 > #spanDiv").click()
    # # 9 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 10 | click | css=#filter_standard_11 > #spanDiv | 
    # # click on 10th standard check box
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_standard_11 > #spanDiv").click()
    # # 11 | click | css=#filter_standard_10 > #spanDiv | 
    # # click on 9th standard check box
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_standard_10 > #spanDiv").click()
    # # 12 | click | css=#filter_standard_12 > #spanDiv | 
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_standard_12 > #spanDiv").click()
    # # 13 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 14 | click | css=#filter_type_sessions > #spanDiv | 
    # # click on session check box 
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_type_sessions > #spanDiv").click()
    # # 15 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 16 | click | css=#filter_type_courses > #spanDiv | 
    # # click on course check box
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_type_courses > #spanDiv").click()
    # # 17 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 18 | click | id=spanDiv | 
    # # click on Math check box
    # self.driver.find_element(By.ID, "spanDiv").click()
    # # 19 | click | css=#filter_curriculum_5 > #spanDiv | 
    # # click on CBSE option
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_curriculum_5 > #spanDiv").click()
    # # 20 | click | css=#filter_standard_10 > #spanDiv | 
    # #  click on 9th standard check box
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_standard_10 > #spanDiv").click()
    # # 21 | click | css=#filter_standard_9 > #spanDiv | 
    # # click on 8th standard check box
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_standard_9 > #spanDiv").click()
    # # 22 | click | css=#filter_standard_10 > #spanDiv | 
    # # click on 10th standard check box
    # self.driver.find_element(By.CSS_SELECTOR, "#filter_standard_10 > #spanDiv").click()
    # # 23 | click | css=.fqFwXV:nth-child(3) > .material-symbols-outlined | 
    # # remove standard filter from breadcrumbs 
    # self.driver.find_element(By.CSS_SELECTOR, ".fqFwXV:nth-child(3) > .material-symbols-outlined").click()
    # # 24 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 25 | click | css=.gEAsKT > .bWxOKe | 
    # # click on view all in course so it will search all course on search page it self
    # self.driver.find_element(By.CSS_SELECTOR, ".gEAsKT > .bWxOKe").click()
    # # 26 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 27 | click | css=.glDbhq:nth-child(1) .bWxOKe | 
    # # click on view detail on first course it will redirect login page and click back button from browser
    # self.driver.find_element(By.CSS_SELECTOR, ".glDbhq:nth-child(1) .bWxOKe").click()
    # # 28 | click | css=.dTuERj:nth-child(1) .bWxOKe | 
    # # click on 1st session view detail option
    # self.driver.find_element(By.CSS_SELECTOR, ".dTuERj:nth-child(1) .bWxOKe").click()
    # # 29 | click | id=inputExploreBtn | 
    # # click on explore option so it will refresh/clear all data and come to search page again
    # self.driver.find_element(By.ID, "inputExploreBtn").click()
    # # 30 | click | css=.gfWXHb | 
    # # click on search bar on search page
    # self.driver.find_element(By.CSS_SELECTOR, ".gfWXHb").click()
    # # 31 | type | css=.gfWXHb | Math
    # # type math on search bar on browsesearch page
    # self.driver.find_element(By.CSS_SELECTOR, ".gfWXHb").send_keys("Math")
    # # 32 | click | css=.dmkMWQ > .material-icons | 
    # # click on search icon
    # self.driver.find_element(By.CSS_SELECTOR, ".dmkMWQ > .material-icons").click()
    # # 33 | click | css=.kfDjoJ | 
    # self.driver.find_element(By.CSS_SELECTOR, ".kfDjoJ").click()
    # # 34 | click | css=.kfDjoJ | 
    # # double click on sign up page it will open typeform 
    # self.driver.find_element(By.CSS_SELECTOR, ".kfDjoJ").click()
    # # 35 | click | css=.tf-v1-close | 
    # # click on cross icon and type form will close
    # self.driver.find_element(By.CSS_SELECTOR, ".tf-v1-close").click()
    # # 36 | click | css=.kjsDg > .bWxOKe | 
    # # click on sign in page. it will open login page
    # self.driver.find_element(By.CSS_SELECTOR, ".kjsDg > .bWxOKe").click()
  
