# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
options = Options()

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

class TestP1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    #webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self,method):
    self.driver.quit()
  
  def test_p1(self):
    # Test name: P1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1440x804 | 
    self.driver.set_window_size(1440, 804)
    # 3 | click | id=APjFqb | 
    searchBox=self.driver.find_element(By.ID, "APjFqb")
    searchBox.click()
    self.driver.get_screenshot_as_file("screenshot.png")

